version: '3.8'

services:
  app:
    build:
      context: .
      target: runtime
    image: your-org/your-app:latest
    ports:
      - '3000:3000'
    env_file:
      - .env.prod
    environment:
      NODE_ENV: production
    depends_on:
      - db
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:15-alpine
    container_name: pg_prod
    ports:
      - '5432:5432'
    env_file:
      - .env.prod
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata_prod:
