version: '3.8'

services:
  app:
    build:
      context: .
      target: builder
    command: npm run dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://devuser:devpass@db:5432/devdb
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: pg_dev
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

volumes:
  pgdata_dev:
